server:
  port: 9005
  servlet:
    session:
      cookie:
        http-only: false
        secure: false
spring:
  application:
    name: rococo-userdata
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-userdata'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-userdata
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest
rococo-userdata:
  base-uri: "http://127.0.0.1:9005"