server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rococo-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    net.devh.boot.grpc: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
rococo-geo:
  base-uri: "http://127.0.0.1:9001"
rococo-artist:
  base-uri: "http://127.0.0.1:9002"
rococo-museum:
  base-uri: "http://127.0.0.1:9003"
rococo-painting:
  base-uri: "http://127.0.0.1:9004"
rococo-userdata:
  base-uri: "http://127.0.0.1:9005"
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
---